USE ASSIGNMENT3;

CREATE VIEW ACTIVE_TOURS_ORDERS AS
SELECT
    T.NAME AS TOUR_NAME,
    T.START_DATE,
    T.FINISH_DATE,
    O.ID AS ORDER_ID,
    O.ORDER_DATE,
    O.TOTAL_PRICE,
    O.CLIENT_ID
FROM
    TOURS T
JOIN
    ORDERS O ON T.ID = O.TOUR_ID
WHERE
    T.AVAILABILITY = 'available';


CREATE VIEW TOURS_WITH_GUIDES_AND_HOTELS AS
SELECT
    T.NAME AS TOUR_NAME,
    G.NAME AS GUIDE_NAME,
    G.SURNAME AS GUIDE_SURNAME,
    H.NAME AS HOTEL_NAME,
    H.RATING AS HOTEL_RATING
FROM TOURS T
JOIN TOUR_GUIDES TG ON T.ID = TG.TOUR_ID
JOIN GUIDES G ON TG.GUIDE_ID = G.ID
JOIN TOUR_HOTELS TH ON T.ID = TH.TOUR_ID
JOIN HOTELS H ON TH.HOTEL_ID = H.ID
WHERE T.AVAILABILITY = 'available';
